language: node_js
node_js:
- lts/*
addons:
  sauce_connect: true
  hosts:
  - airtap.local
after_success: npm run coverage
env:
  global:
  - secure: 19NXgMyvDps8SFIjUZrviBKmaC2aO5B6ZMXHE2qe2KY+EvktbZ225obtd+35EsDO0bCVFUmZVTqQVBrid0HX1LorQa1aPnwJOUW2rFpHSBJcBt0SUYcWmKMiDT8kNYANqav4dz9VS5mDDJXcWsdcR/N/JIqqShGCwGkorDTAzjXFS1JnLxuS28ibLtDbs93tM0LUfPcawN59n6v0utQKtvLHUdACcf0VCa5eK7mwnFoc/hD0ssmCTe5s3Xd4hLYA8rRMATYuILNGtu+fCkJ5CfMr0/2ygBmENtl2SuODKe7syNVd0IaA4v7JxLC60nyq42rMUMHvbVQEGpQK5yjamjmpxJ1lXSfbxsMlcM68DAgHHOKYIOoiTru9UXWyFKLyCzLL74zbZk/2cE8zVUiz8JbJ5p0soM9wmVt34N0SkFKehb80zrtXDkzEHrB1RrWb1ybw5Zqnx+3OqVtX8gWWTx77c3awjWPN2zvDBTEYy/GOpFIQ5lw9F1Kik0xz0dhjsmXGAP17sKheJqjGjkcd026pUb4FnmbwNt71r41rueL9jaXTBaknh1Q9ndszM5jURSpse8ECk9PxIBO2vX5lnjBevfeWrk0FPEruEyMG1POBoq0TjMEycHAQXCSE8nUINGxvm5XbqyuJXbaygttSgj5lUs/sPfaMp9kDl7cFqT8=
  - secure: 18in8yO5yuP/3wb+Gmm6J8uhmXShQeFcnMp9AGYg+LhJhaWfb2sXBXsHvLzR7BzozqWXUhOaECAzEEbfAD6ufWTkFP5xaYu134wtcJSHQ6peTP4LDNdLe7asRB3zk/oekAmYgWjWNE2ycAVA+sugi4UsKQ3DUtXAoGSwBHeR6e3RmJ10mfo/Cl+q86fBLqzTb3+Gv3+wHZGJAqKQmeGvqDmEaesXMhBHHtR7eGeWNmmsS4ZCvwSLjq9JQFdnBnx284P5qtIiyIqznDFxDgdm/gatH3XHHjJ41jR5IugLrKL2C2bqjKRKlbvzKFs83KQ6sFAXHtjEyYeLjh4+7cBa1zX6JgtNBK3zxDKX39uupXstKVR744lIdTH6Ap9pBmgdZugycSVV68+qGzeLlRwfGJi1aMn1tpNNTdKReClql5RKBmVxUy6A5o1vqam75RBEzxXp+axu6Ngnv2Yu0rRXP5/j3v+jV3MbVulexhqRD7lBgrBeF3ajwOhocnc7WM/S8xlR+nLWjhfRJcWOMp9oWysyWcnnnVQUabfgXKxJeBpBivJ8oDPgSjSTCa5kQQK4TooZkTTEMvvVNIrYz0/tLqKWCuWhyVo6x6s0lEfZRyQ4xlMUnm5H2cnbajF/z/jTPOTWDisK+O3BZ4RKV/+xznpIE8fU0BLWyfNU7aT5qRA=
