language: node_js
node_js:
- lts/*
addons:
  sauce_connect: true
  hosts:
  - airtap.local
after_success: npm run coverage
env:
  global:
  - secure: QeHZf6YnqyxE1jlMYHNez/BOQv62BcQjzWG7rDrUaecFSmzi3lioTdKxz7Sr/VPv1y1fYzumq4eIQd1Vr/og2PySWyGAFEta+x8gLIY+IJECAfLgHO0ahiW/jD3HD49Nnw9FemMoa585cwqpgnMAJPBS37pAkQoVq7gelBAyOIznyFrM9JF6V/wNLINCq61p229+kNuT40WJoIv17f9mxcLcl5KzhoytsTx+DR/g3/qMIQGzXc1DfxipvXIyQUyyZ0O+6jyKdWH5PQFpOTS8g78wq5vZB6iHHUnB6uXBZ1g+wErGRlKi65GHsDgYoF4G+BUTNSJFizvNUBY0zoYe0dXPZdLeO5bMQj7fajdsl+wmMk/sstX6dpsiUu+OyHPurzBhcF2/2zfV9XuzRl0OlRGQE81rGnm9W9gG1k36eCdl1TKuWXBisKca+ufyKv+7gzcTNhC0eG5rftDPehiRh3ImIDzFZoVUtAmxwvnnbjrJvTT8Px2zUlS0ZwI41AZkKFOzewqqqnGYDVAmhMkG1m24ItSHu5ekvZR5rPxA49G+NztypqkUfm4eA/OQbivbtf+MhG/2pWTf35+GY9YRrwqyQR5Cwhm97wXwdl8SFayBsbcKXAj0NShuFXMKJ74HLnbPrwhCI8m5AHvt7w8iiNHR9nPBLahilgd8ZV89+pE=
  - secure: dQWXHSXf1iVrkR+u6Sij9U37qLO9ntztqRHvzUJnr949s56VYYDhTOYJOanYFTpYD1HE46BTpNRZSTTO1Qw1eGGGJ+DXbfceSEM0eAIPoMuSAuCyWTfpTTCgpEPSjsH5D88Xj5G0JG+F+L7C/Aew8cRKkQvjsiFeNBgU4JfWwGsQE53AWcxj262I32ctdyA9NKNzEMF15ZqVMMpLwV0MFB5ivkxRahRMiDxVp1xtKXpV9mXDk0rg4l9V7jMIuXYLYFOwgj6Eeww5NbNpbdO37oaPkEKGvI8fVcUeuiMPREfM5hE7tU2XS1i1sOBXUMRl1uOUM99rm5bUj4Qy2emQQjj/kGlFaUQMPZBJlvS/TV0tzRuoT19vvNM0PkmqdlljqDDVNLJW0260GK5pPRItB7icmyTTQKO62gwGouClaQsMdCSHDpOoAvSW8nIHDNxCbOorDBw0Mj5fcdQzeWW5ImS0cjhXsHUo1cLApnxXPqXIJJPfQLZFEaWFUXOAkj5RjJo3K5E5dwhb9n9fimOCvKQjyVrimwDixsqg//tfVOa1aMcbC1RrTCFVsg+bxrAJW6XaDCABwq0FuIzoGH7of7deqd4yMEgzXzmxrwv7FXHFqfvrmCMahURFEPcTwiMsxEeFdNHrZtpAHDxdNaa8RjIadgpZo0KxiwofgM5RHHs=
